FROM python:3.6.7-slim

MAINTAINER Bedapudi Praneeth "praneeth@notai.tech"

RUN apt-get update && apt-get install -y build-essential gcc

RUN pip3 install Cython

RUN pip3 install requests gevent falcon gunicorn

WORKDIR /app

ADD . /app

CMD ["bash", "_run.sh"]
